### ISSUE TITLE
can not create VMs

### ISSUE THREAD

**Issue by jihoonlee0703** [Seitanas/kvm-vdi#150]
Hi all
I have some problem about create VMs

I made bridge(br0)
os : centos7

error messages are here

thank you
===================================================
Got error while editing doamin XML : Traceback (most recent call last):
File "/usr/local/VDI//vdi-xmledit", line 24, in 
tree = ET.parse('/etc/libvirt/qemu/' + vmname+'.xml')
File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
tree.parse(source, parser)
File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 647, in parse
source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/etc/libvirt/qemu/windows4.xml'
======================================================

**Comment by Seitanas** [comment]
It seems that vm was not created. To little information to define problem.
